### ISSUE TITLE
NumPY error when installed thru singularity and conda

### ISSUE THREAD

**Issue by ccbruels** [HKU-BAL/ClairS#35]
Hi,

I've run ClairS and ClairS-TO previously, and installed the current versions of both last week. Now I get the same NumPY error when I try to run the previous version, the current version, and when I install using conda or singularity. 

The main issue seems to be:

=====
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
=====

The full error messages include:

=======
[INFO] Check environment variables
[INFO] Call variant in contigs: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY
[INFO] Chunk number for each contig: 40 37 32 32 31 30 29 27 25 27 25 25 25 26 21 20 20 19 13 34 19
[INFO] 1/7 Call variants using pileup model

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 105, in <module>
    main()
  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 92, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/opt/conda/envs/clairs/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/clairs/bin/clair3/CallVariantsFromCffi.py", line 3, in <module>
    import tensorflow as tf
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 105, in <module>
    main()
  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 92, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/opt/conda/envs/clairs/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/clairs/bin/clair3/CallVariantsFromCffi.py", line 3, in <module>
    import tensorflow as tf
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 95, in <module>
    from tensorflow.python.data.experimental import service
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 387, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 26, in <module>
    from tensorflow.python.lib.core import _pywrap_bfloat16
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 105, in <module>
    main()
  File "/opt/conda/envs/clairs/bin/scripts/../clair3.py", line 92, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/opt/conda/envs/clairs/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/envs/clairs/bin/clair3/CallVariantsFromCffi.py", line 3, in <module>
    import tensorflow as tf
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 95, in <module>
    from tensorflow.python.data.experimental import service
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 387, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "/opt/conda/envs/clairs/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 29, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

**Comment by ccbruels** [comment]
Update: I was able to downgrade NumPY to v1.22.4 which seems to have resolved the issue as variants are now being called.

Apparently NumPY was recently updated. Could you please post info about what version of NumPY to use when installing ClairS and presumably ClairS-TO and Clair3?

Thanks!
